version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/landing"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/desktop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/extension"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
